services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: pivote
      POSTGRES_PASSWORD: pivote123
      POSTGRES_DB: pivotedb
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit-host
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped
  redis:
    image: redis:7
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  rabbitmq-data:
  postgres-data:
  redis-data:
